import type { Metadata } from "next";
// FIX: The Geist font is a local font from the 'geist' package, NOT a Google Font.
// We import the specific font styles (Sans and Mono) directly from the package.
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

import "./globals.css";

// We no longer need to call the functions, as the imports directly provide the font objects.
// We rename the font objects to match the original variables for clarity in the body class.
const geistSans = GeistSans;
const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}